# Generated by Django 4.2.11 on 2024-05-07 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunters", "0002_application_companyprofile_image_userprofile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image",
        ),
        migrations.AlterField(
            model_name="job",
            name="posted_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
