# Generated by Django 4.2.11 on 2024-05-08 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job_hunters", "0004_userprofile_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="cover_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_cover",
                to="job_hunters.image",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companyprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="webpage_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
