# Generated by Django 4.2.11 on 2024-05-08 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job_hunters", "0005_alter_companyprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
