# Generated by Django 4.2.11 on 2024-05-08 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunters", "0006_application_applicant"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="applied_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
