# Generated by Django 4.2.11 on 2024-05-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunters", "0008_alter_companyprofile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
    ]
