# Generated by Django 4.2.11 on 2024-05-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunters", "0009_alter_experience_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("REJECTED", "Rejected"),
                    ("ACCEPTED", "Accepted"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
    ]
